# Generated by Django 3.1 on 2020-08-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('number', models.CharField(max_length=32)),
                ('subject', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
    ]
