# Generated by Django 3.1 on 2020-08-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkcrafter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
