# Generated by Django 3.1 on 2020-08-10 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkcrafter', '0003_auto_20200810_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('delivery', models.FileField(upload_to='files')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='done', to='homeworkcrafter.homework')),
            ],
        ),
    ]
