# Generated by Django 3.1 on 2020-08-10 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkcrafter', '0005_auto_20200810_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='delivery',
            new_name='deliveredfile',
        ),
    ]
