# Generated by Django 3.1 on 2020-08-11 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkcrafter', '0006_auto_20200810_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='id',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='homework',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='homeworkcrafter.homework'),
        ),
    ]
