# Generated by Django 3.1 on 2020-08-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkcrafter', '0007_auto_20200810_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='deliveredfile',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
