# Generated by Django 3.1 on 2020-08-11 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkcrafter', '0009_auto_20200810_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='done',
        ),
    ]
