# Generated by Django 3.1 on 2020-08-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkcrafter', '0010_remove_homework_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
