# Generated by Django 3.1 on 2020-08-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkcrafter', '0012_auto_20200811_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='erase',
            field=models.BooleanField(default=False),
        ),
    ]
