# Generated by Django 3.1 on 2020-08-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkcrafter', '0016_auto_20200811_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
