# Generated by Django 3.1 on 2020-08-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkcrafter', '0017_auto_20200811_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='instruction_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
