# Generated by Django 3.1 on 2020-08-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkcrafter', '0018_homework_instruction_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='level',
            field=models.CharField(default='bachillerato', max_length=32),
        ),
    ]
