# Generated by Django 3.1 on 2020-08-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkcrafter', '0020_auto_20200814_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='name',
            field=models.CharField(default='p', max_length=32),
            preserve_default=False,
        ),
    ]
