# Generated by Django 3.1 on 2020-08-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkcrafter', '0023_auto_20200817_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='time',
            field=models.TimeField(default='17:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homework',
            name='date',
            field=models.DateField(),
        ),
    ]
