# Generated by Django 3.1 on 2020-08-12 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkcrafter', '0017_auto_20200811_2132'),
        ('staff', '0004_auto_20200811_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=5000, null=True)),
                ('homework', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='homeworkcrafter.homework')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='staff.profile')),
            ],
        ),
    ]
