# Generated by Django 3.1 on 2020-08-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.IntegerField()),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
